import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#414750',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        outline: '#727781',
        'outline-variant': '#c1c7d2',
        'surface-tint': '#1261a3',
        primary: '#004275',
        'on-primary': '#ffffff',
        'primary-container': '#005a9c',
        'on-primary-container': '#afd1ff',
        'inverse-primary': '#a1c9ff',
        secondary: '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        tertiary: '#3b4248',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#52595f',
        'on-tertiary-container': '#c9cfd7',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#a1c9ff',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#00487f',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#dde3eb',
        'tertiary-fixed-dim': '#c1c7cf',
        'on-tertiary-fixed': '#161c22',
        'on-tertiary-fixed-variant': '#41474e',
        background: '#f9f9ff',
        'on-background': '#111c2d',
        'surface-variant': '#d8e3fb',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        'sidebar-width': '280px',
        'container-max-width': '1200px',
        gutter: '24px',
        'margin-page': '40px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Noto Sans SC', 'Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        'headline-lg': ['Noto Sans SC', 'system-ui', 'sans-serif'],
        'headline-md': ['Noto Sans SC', 'system-ui', 'sans-serif'],
        'headline-sm': ['Noto Sans SC', 'system-ui', 'sans-serif'],
        'body-lg': ['Noto Sans SC', 'system-ui', 'sans-serif'],
        'body-md': ['Noto Sans SC', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.4', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.8', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 4px 12px rgba(0, 0, 0, 0.05)',
        modal: '0 12px 32px rgba(0, 50, 100, 0.08)',
      },
    },
  },
} satisfies Config
